import Header from "@/ui/Header";
import "./globals.css";
import SaveUserInfo from "./SaveUserInfo";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <SaveUserInfo />
      </body>
    </html>
  );
}
